import type { ProjectConfig, OutputFile } from '@/types';
import { hasSecretCheck } from './sandboxScripts';

// ── emitEvent script (P1: Log 层接线) ──

function renderEmitEventScript(): string {
  return [
    '#!/usr/bin/env bash',
    '# emit-event.sh — Append structured event to .harness/log/events.jsonl',
    '# Fires on every PostToolUse to record runtime events for the Log layer.',
    '# Also parses tdd.json to surface coverage requirements during build stage.',
    '# Exit 0 always (never block — logging is best-effort).',
    '',
    'set -uo pipefail',
    '',
    'INPUT=$(cat || true)',
    'LOG_DIR=".harness/log"',
    'LOG_FILE="$LOG_DIR/events.jsonl"',
    '',
    'mkdir -p "$LOG_DIR"',
    '',
    '# Detect mode: sprint (state.json with sprint.current) or standalone (no sprint context)',
    'detect_mode() {',
    '  if [ -f ".harness/state.json" ]; then',
    '    CURRENT=$(jq -r \'.sprint.current // empty\' ".harness/state.json" 2>/dev/null)',
    '    if [ -n "$CURRENT" ]; then',
    '      echo "sprint"',
    '      return',
    '    fi',
    '  fi',
    '  echo "standalone"',
    '}',
    '',
    'MODE=$(detect_mode)',
    '',
    '# Extract tool_name from stdin JSON (Claude Code format: {"tool_name":"Bash","tool_input":{...}})',
    'TOOL="unknown"',
    'if command -v jq >/dev/null 2>&1; then',
    '  TOOL=$(echo "$INPUT" | jq -r ".tool_name // \\"unknown\\"" 2>/dev/null || echo "unknown")',
    'else',
    '  TOOL=$(echo "$INPUT" | grep -o \'"tool_name":"[^"]*"\' | head-1 | sed \'s/"tool_name":"//;s/"//\' || echo "unknown")',
    'fi',
    '',
    '# Read current stage and role from files (written by CLAUDE.md protocol)',
    'if [ "$MODE" = "sprint" ]; then',
    '  STAGE=$(cat .harness/current-stage 2>/dev/null || echo "unknown")',
    '  ROLE=$(cat .harness/current-role 2>/dev/null || echo "unknown")',
    'else',
    '  STAGE="standalone"',
    '  ROLE="external"',
    'fi',
    '',
    '# Build event JSON',
    'EVENT=$(printf \'{"ts":"%s","tool":"%s","phase":"%s","role":"%s"}\\n\' \\',
    '  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \\',
    '  "$TOOL" \\',
    '  "$STAGE" \\',
    '  "$ROLE")',
    '',
    'echo "$EVENT" >> "$LOG_FILE"',
    '',
    '# Auto-parse tdd.json during build stage to surface coverage gate (sprint mode only)',
    'if [ "$MODE" = "sprint" ]; then',
    '  TDD_FILE=".harness/constraints/tdd.json"',
    '  if [ -f "$TDD_FILE" ] && [ "$STAGE" = "build" ] && [ "$TOOL" = "Bash" ]; then',
    '    if command -v jq >/dev/null 2>&1; then',
    '      MIN_COV=$(jq -r ".coverage.min_percent // 0" "$TDD_FILE" 2>/dev/null)',
    '      NO_SKIP=$(jq -r ".tests.no_skip // true" "$TDD_FILE" 2>/dev/null)',
    '      MAX_RETRY=$(jq -r ".retry.max_attempts // 3" "$TDD_FILE" 2>/dev/null)',
    '      if [ "$MIN_COV" != "0" ]; then',
    '        echo "[Harness] TDD Gate: coverage >= ${MIN_COV}%, no_skip=${NO_SKIP}, max_retry=${MAX_RETRY}"',
    '      fi',
    '    fi',
    '  fi',
    'fi',
    '',
    'exit 0',
  ].join('\n');
}

// ── Guard script (P1: Hands 层权限守卫) ──

function renderGuardScript(): string {
  return [
    '#!/usr/bin/env bash',
    '# guard.sh — PreToolUse: enforce stage/role constraints from constraints.json',
    '# Reads state.json + constraints.json → allow (exit 0) or block (exit 2)',
    '# .harness/ and .claude/hooks/ and .claude/scripts/ are never writable — AI cannot tamper.',
    '',
    'set -uo pipefail',
    '',
    'INPUT=$(cat || true)',
    'HARNESS=".harness"',
    '',
    '# Detect mode: sprint (state.json with sprint.current) or standalone (no sprint context)',
    'detect_mode() {',
    '  if [ -f "$HARNESS/state.json" ]; then',
    '    CURRENT=$(jq -r \'.sprint.current // empty\' "$HARNESS/state.json" 2>/dev/null)',
    '    if [ -n "$CURRENT" ]; then',
    '      echo "sprint"',
    '      return',
    '    fi',
    '  fi',
    '  echo "standalone"',
    '}',
    '',
    'MODE=$(detect_mode)',
    '',
    '# Log blocked operations for compliance audit',
    'log_block() {',
    '  local reason="$1"',
    '  mkdir -p "$HARNESS/log"',
    '  printf \'{"ts":"%s","stage":"%s","tool":"%s","file":"%s","reason":"%s"}\\n\' \\',
    '    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$STAGE" "$TOOL" "$FILE" "$reason" >> "$HARNESS/log/blocks.jsonl"',
    '}',
    '',
    '# Extract tool_name and file_path from stdin JSON',
    'TOOL=""',
    'FILE=""',
    'if command -v jq >/dev/null 2>&1; then',
    '  TOOL=$(echo "$INPUT" | jq -r ".tool_name // \\"\\\"" 2>/dev/null || echo "")',
    '  FILE=$(echo "$INPUT" | jq -r ".tool_input.file_path // .tool_input.command // \\"\\\"" 2>/dev/null || echo "")',
    'else',
    '  TOOL=$(echo "$INPUT" | grep -o \'"tool_name":"[^"]*"\' | head -1 | sed \'s/"tool_name":"//;s/"//\' 2>/dev/null || echo "")',
    '  FILE=$(echo "$INPUT" | grep -oE \'"file_path":"[^"]*"\' | head -1 | sed \'s/"file_path":"//;s/"//\' 2>/dev/null || echo "")',
    'fi',
    '',
    'if [ -z "$TOOL" ]; then',
    '  exit 0',
    'fi',
    '',
    '# ── Standalone mode: security boundary only ──',
    'if [ "$MODE" = "standalone" ]; then',
    '  STAGE="standalone"',
    '',
    '  # Protect critical directories from Write/Edit',
    '  if [[ "$TOOL" == "Write" || "$TOOL" == "Edit" ]]; then',
    '    case "$FILE" in',
    '      .harness/*)',
    '        echo "BLOCKED: Cannot modify .harness/ — state is managed by hooks only" >&2',
    '        log_block "write-to-harness"',
    '        exit 2',
    '        ;;',
    '      .claude/hooks/*|.claude/scripts/*)',
    '        echo "BLOCKED: Cannot modify .claude/hooks/ or .claude/scripts/ — enforcement scripts are read-only" >&2',
    '        log_block "write-to-hooks"',
    '        exit 2',
    '        ;;',
    '    esac',
    '  fi',
    '',
    '  # Bash tool: inspect command string for writes to protected directories',
    '  if [[ "$TOOL" == "Bash" ]]; then',
    '    CMD="$FILE"',
    '    if echo "$CMD" | grep -qE \'(>|>>)\\s*.harness/|cat\\s+>\\s*.harness/|tee\\s+.harness/|cp\\s+.*\\.harness/|mv\\s+.*\\.harness/|install\\s+.*\\.harness/\'; then',
    '      echo "BLOCKED: Cannot write to .harness/ via Bash — state is managed by hooks only" >&2',
    '      log_block "bash-write-to-harness"',
    '      exit 2',
    '    fi',
    '    if echo "$CMD" | grep -qE \'(>|>>)\\s*.claude/hooks/|cat\\s+>\\s*.claude/hooks/|tee\\s+.claude/hooks/|cp\\s+.*\\.claude/hooks/|mv\\s+.*\\.claude/hooks/\'; then',
    '      echo "BLOCKED: Cannot write to .claude/hooks/ via Bash — enforcement scripts are read-only" >&2',
    '      log_block "bash-write-to-hooks"',
    '      exit 2',
    '    fi',
    '    if echo "$CMD" | grep -qE \'(>|>>)\\s*.claude/scripts/|cat\\s+>\\s*.claude/scripts/|tee\\s+.claude/scripts/|cp\\s+.*\\.claude/scripts/|mv\\s+.*\\.claude/scripts/\'; then',
    '      echo "BLOCKED: Cannot write to .claude/scripts/ via Bash — enforcement scripts are read-only" >&2',
    '      log_block "bash-write-to-scripts"',
    '      exit 2',
    '    fi',
    '    if echo "$CMD" | grep -qE \'state\\.json(\\.tmp)?|constraints\\.json\'; then',
    '      echo "BLOCKED: Cannot modify state.json or constraints.json via Bash — managed by hooks only" >&2',
    '      log_block "bash-modify-state"',
    '      exit 2',
    '    fi',
    '',
    '    # Dangerous command patterns (global safety boundary)',
    '    LOWER_CMD=$(echo "$CMD" | tr \'[:upper:]\' \'[:lower:]\')',
    '    DANGER_PATTERNS=(\'rm -rf\' \'rm -r /\' \'drop table\' \'truncate table\' \'delete from\' \':(){ :|:& };:\' \'dd if=/dev/zero\' \'mkfs.\' \'> /dev/sd\')',
    '    for PATTERN in "${DANGER_PATTERNS[@]}"; do',
    '      if echo "$LOWER_CMD" | grep -q "$PATTERN"; then',
    '        echo "BLOCKED: Command matches dangerous pattern: $PATTERN" >&2',
    '        log_block "dangerous-command"',
    '        exit 2',
    '      fi',
    '    done',
    '  fi',
    '',
    '  # Standalone mode: no stage rules, no tool deny lists, no write path checks',
    '  exit 0',
    'fi',
    '',
    '# ── Sprint mode: constraint enforcement (guard-marker gated) ──',
    '',
    '# Check sprint-guard-active marker — if absent, skip write path/tool restrictions.',
    '# This allows skills (invoked outside sprint flow) to write freely.',
    '# Only critical directory protection (.harness/, .claude/hooks/, .claude/scripts/) remains.',
    'GUARD_MARKER="$HARNESS/sprint-guard-active"',
    'GUARD_ACTIVE=false',
    'if [ -f "$GUARD_MARKER" ]; then',
    '  GUARD_ACTIVE=true',
    'fi',
    '',
    '# Require state.json and constraints.json',
    'if [ ! -f "$HARNESS/state.json" ] || [ ! -f "$HARNESS/constraints.json" ]; then',
    '  exit 0',
    'fi',
    '',
    '# Read current stage from state.json',
    'STATE=$(cat "$HARNESS/state.json")',
    'STAGE=$(echo "$STATE" | jq -r \'.sprint.current // "think"\')',
    '',
    '# Protect critical directories from writes (security boundary)',
    '# Covers Write, Edit, and Bash (command-level inspection)',
    '',
    'if [[ "$TOOL" == "Write" || "$TOOL" == "Edit" ]]; then',
    '  case "$FILE" in',
    '    .harness/*)',
    '      echo "BLOCKED: Cannot modify .harness/ — state is managed by hooks only" >&2',
    '      log_block "write-to-harness"',
    '      exit 2',
    '      ;;',
    '    .claude/hooks/*|.claude/scripts/*)',
    '      echo "BLOCKED: Cannot modify .claude/hooks/ or .claude/scripts/ — enforcement scripts are read-only" >&2',
    '      log_block "write-to-hooks"',
    '      exit 2',
    '      ;;',
    '  esac',
    'fi',
    '',
    '# Bash tool: inspect command string for writes to protected directories',
    'if [[ "$TOOL" == "Bash" ]]; then',
    '  CMD="$FILE"',
    '  # Detect redirect/append targets: > or >> followed by a protected path',
    '  if echo "$CMD" | grep -qE \'(>|>>)\\s*.harness/|cat\\s+>\\s*.harness/|tee\\s+.harness/|cp\\s+.*\\.harness/|mv\\s+.*\\.harness/|install\\s+.*\\.harness/\'; then',
    '    echo "BLOCKED: Cannot write to .harness/ via Bash — state is managed by hooks only" >&2',
    '    log_block "bash-write-to-harness"',
    '    exit 2',
    '  fi',
    '  if echo "$CMD" | grep -qE \'(>|>>)\\s*.claude/hooks/|cat\\s+>\\s*.claude/hooks/|tee\\s+.claude/hooks/|cp\\s+.*\\.claude/hooks/|mv\\s+.*\\.claude/hooks/\'; then',
    '    echo "BLOCKED: Cannot write to .claude/hooks/ via Bash — enforcement scripts are read-only" >&2',
    '    log_block "bash-write-to-hooks"',
    '    exit 2',
    '  fi',
    '  if echo "$CMD" | grep -qE \'(>|>>)\\s*.claude/scripts/|cat\\s+>\\s*.claude/scripts/|tee\\s+.claude/scripts/|cp\\s+.*\\.claude/scripts/|mv\\s+.*\\.claude/scripts/\'; then',
    '    echo "BLOCKED: Cannot write to .claude/scripts/ via Bash — enforcement scripts are read-only" >&2',
    '    log_block "bash-write-to-scripts"',
    '    exit 2',
    '  fi',
    '  # Also catch: jq in-place writes to state.json (jq ... > file.tmp && mv pattern)',
    '  if echo "$CMD" | grep -qE \'state\\.json(\\.tmp)?|constraints\\.json\'; then',
    '    echo "BLOCKED: Cannot modify state.json or constraints.json via Bash — managed by hooks only" >&2',
    '    log_block "bash-modify-state"',
    '    exit 2',
    '  fi',
    '',
    '  # Dangerous command patterns (global safety boundary)',
    '  LOWER_CMD=$(echo "$CMD" | tr \'[:upper:]\' \'[:lower:]\')',
    '  DANGER_PATTERNS=(\'rm -rf\' \'rm -r /\' \'drop table\' \'truncate table\' \'delete from\' \':(){ :|:& };:\' \'dd if=/dev/zero\' \'mkfs.\' \'> /dev/sd\')',
    '  for PATTERN in "${DANGER_PATTERNS[@]}"; do',
    '    if echo "$LOWER_CMD" | grep -q "$PATTERN"; then',
    '      echo "BLOCKED: Command matches dangerous pattern: $PATTERN" >&2',
    '      log_block "dangerous-command"',
    '      exit 2',
    '    fi',
    '  done',
    'fi',
    '',
    '# ── Skill bypass: auto-pause sprint rules during skill execution ──',
    '# When a Skill tool is invoked, create bypass marker.',
    '# Guard skips sprint stage rules (tool deny, write paths) while bypass active.',
    '# Security boundary (.harness/, .claude/hooks/ protection) always enforced.',
    '# Bypass cleared automatically on next sprint stage transition.',
    '# Safety net: auto-expires after 30 minutes to prevent stale bypasses.',
    'SKILL_BYPASS="$HARNESS/skill-bypass"',
    '',
    'if [[ "$TOOL" == "Skill" ]]; then',
    '  date +%s > "$SKILL_BYPASS"',
    'fi',
    '',
    'if [ -f "$SKILL_BYPASS" ]; then',
    '  BYPASS_TS=$(cat "$SKILL_BYPASS" 2>/dev/null || echo 0)',
    '  NOW=$(date +%s)',
    '  AGE=$((NOW - BYPASS_TS))',
    '  if [ "$BYPASS_TS" != "0" ] && [ "$AGE" -lt 1800 ]; then',
    '    exit 0',
    '  else',
    '    rm -f "$SKILL_BYPASS"',
    '  fi',
    'fi',
    '',
    '# ── Sprint stage rules: only enforced when guard marker is active ──',
    'if [[ "$GUARD_ACTIVE" == true ]]; then',
    '',
    '  # If jq missing, warn and skip sprint rules (guidance, not control)',
    '  if ! command -v jq >/dev/null 2>&1; then',
    '    echo "[Harness] WARNING: jq missing, sprint rules skipped. Install: brew install jq" >&2',
    '    log_block "jq-missing"',
    '    exit 0',
    '  fi',
    '',
    '  # Read stage rules from constraints.json using jq',
    '  STAGE_CFG=$(jq --arg name "$STAGE" \'.stages[] | select(.name == $name)\' "$HARNESS/constraints.json" 2>/dev/null)',
    '',
    '  if [ -z "$STAGE_CFG" ]; then',
    '    exit 0',
    '  fi',
    '',
    '  # Check deny list — but exempt harness-managed scripts from Bash deny',
    '  # Slash commands invoke bash .claude/hooks/transition.sh which must always work',
    '  SKIP_DENY=false',
    '  if [[ "$TOOL" == "Bash" ]] && echo "$FILE" | grep -qE \'\.(claude/(hooks|scripts)/|harness/scripts/)\'; then',
    '    SKIP_DENY=true',
    '  fi',
    '',
    '  if [[ "$SKIP_DENY" == false ]]; then',
    '    DENIED=$(echo "$STAGE_CFG" | jq -r \'.tools.deny[]\' 2>/dev/null)',
    '    if echo "$DENIED" | grep -qx "$TOOL"; then',
    '      # Check safeBash whitelist — allow non-destructive commands even when Bash is denied',
    '      if [[ "$TOOL" == "Bash" ]]; then',
    '        SAFE_CMDS=$(echo "$STAGE_CFG" | jq -r \'.tools.safeBash[]\' 2>/dev/null)',
    '        FIRST_WORD=$(echo "$FILE" | awk \'{print $1}\' | sed "s|.*/||" )',
    '        if echo "$SAFE_CMDS" | grep -qx "$FIRST_WORD"; then',
    '          exit 0',
    '        fi',
    '      fi',
    '      echo "[Harness] WARNING: Tool \\"$TOOL\\" not recommended in $STAGE stage" >&2',
    '      log_block "tool-denied"',
    '      exit 0',
    '    fi',
    '  fi',
    '',
    '  # Check write path permissions',
    '  if [[ "$TOOL" == "Write" || "$TOOL" == "Edit" ]]; then',
    '    if [ -n "$FILE" ]; then',
    '      # Normalize to relative path — Write/Edit tools may pass absolute paths',
    '      MATCH_FILE="${FILE#$(pwd)/}"',
    '      ALLOWED_PATHS=$(echo "$STAGE_CFG" | jq -r \'.paths.write[]\' 2>/dev/null)',
    '      MATCH=false',
    '      while IFS= read -r pattern; do',
    '        [ -z "$pattern" ] && continue',
    '        # shellcheck disable=SC2254',
    '        case "$MATCH_FILE" in',
    '          $pattern) MATCH=true; break ;;',
    '        esac',
    '      done <<< "$ALLOWED_PATHS"',
    '      if [[ "$MATCH" == false ]]; then',
    '        echo "[Harness] WARNING: Writing to \\"$FILE\\" outside recommended paths for $STAGE stage" >&2',
    '        echo "Recommended paths: $(echo "$ALLOWED_PATHS" | tr \'\\n\' \' \')" >&2',
    '        log_block "write-path-denied"',
    '        exit 0',
    '      fi',
    '    fi',
    '  fi',
    '',
    'fi # end GUARD_ACTIVE',
    '',
    'exit 0',
  ].join('\n');
}

// ── Advance script (PostToolUse: gate checking) ──

function renderAdvanceScript(): string {
  return [
    '#!/usr/bin/env bash',
    '# advance.sh — PostToolUse: check gates and update state.json',
    '# After each tool use, checks if current stage gates are satisfied.',
    '# Updates state.json gates.{stage}.passed = true when all gates pass.',
    '',
    'set -uo pipefail',
    '',
    'HARNESS=".harness"',
    '',
    '# Detect mode: sprint (state.json with sprint.current) or standalone (no sprint context)',
    'detect_mode() {',
    '  if [ -f "$HARNESS/state.json" ]; then',
    '    CURRENT=$(jq -r \'.sprint.current // empty\' "$HARNESS/state.json" 2>/dev/null)',
    '    if [ -n "$CURRENT" ]; then',
    '      echo "sprint"',
    '      return',
    '    fi',
    '  fi',
    '  echo "standalone"',
    '}',
    '',
    'MODE=$(detect_mode)',
    '',
    'if [ "$MODE" = "standalone" ]; then',
    '  # No sprint context → no file gates to check',
    '  exit 0',
    'fi',
    '',
    '# ── Skill bypass: skip gate checking during skill execution ──',
    'SKILL_BYPASS="$HARNESS/skill-bypass"',
    'if [ -f "$SKILL_BYPASS" ]; then',
    '  BYPASS_TS=$(cat "$SKILL_BYPASS" 2>/dev/null || echo 0)',
    '  NOW=$(date +%s)',
    '  AGE=$((NOW - BYPASS_TS))',
    '  if [ "$BYPASS_TS" != "0" ] && [ "$AGE" -lt 1800 ]; then',
    '    exit 0',
    '  else',
    '    rm -f "$SKILL_BYPASS"',
    '  fi',
    'fi',
    '',
    'if ! command -v jq >/dev/null 2>&1; then',
    '  # PostToolUse should not block — log warning only',
    '  echo "[Harness] WARNING: jq missing, gate checking disabled. Install: brew install jq" >&2',
    '  exit 0',
    'fi',
    '',
    'STATE=$(cat "$HARNESS/state.json")',
    'STAGE=$(echo "$STATE" | jq -r \'.sprint.current // "think"\')',
    '',
    '# Skip if already passed',
    'ALREADY=$(echo "$STATE" | jq -r ".gates.\\"$STAGE\\".passed // false")',
    'if [ "$ALREADY" = "true" ]; then',
    '  exit 0',
    'fi',
    '',
    '# Performance: only run command gates on explicit gate check requests,',
    '# not on every PostToolUse. Command gates are deferred to transition.sh.',
    '# We check only file-based gates here.',
    '',
    '# Get gates for current stage from constraints.json',
    'GATES=$(jq --arg name "$STAGE" \'.stages[] | select(.name == $name) | .gates\' "$HARNESS/constraints.json" 2>/dev/null)',
    'if [ -z "$GATES" ] || [ "$GATES" = "null" ]; then',
    '  exit 0',
    'fi',
    '',
    'GATE_COUNT=$(echo "$GATES" | jq \'length\' 2>/dev/null)',
    'if [ "$GATE_COUNT" -eq 0 ]; then',
    '  echo "$STATE" | jq --arg s "$STAGE" \'.gates[$s].passed = true\' > "$HARNESS/state.json.tmp" && mv "$HARNESS/state.json.tmp" "$HARNESS/state.json"',
    '  exit 0',
    'fi',
    '',
    'ALL_PASS=true',
    'ARTIFACTS="[]"',
    'HAS_COMMAND_GATE=false',
    '',
    'for i in $(seq 0 $((GATE_COUNT - 1))); do',
    '  TYPE=$(echo "$GATES" | jq -r ".[$i].type" 2>/dev/null)',
    '',
    '  # Skip command gates in PostToolUse — too expensive to run on every tool call.',
    '  # Command gates are checked in transition.sh when advancing to next stage.',
    '  if [ "$TYPE" = "command_exit" ]; then',
    '    HAS_COMMAND_GATE=true',
    '    continue',
    '  fi',
    '',
    '  PATTERN=$(echo "$GATES" | jq -r ".[$i].pattern" 2>/dev/null)',
    '  ID=$(echo "$GATES" | jq -r ".[$i].id" 2>/dev/null)',
    '',
    '  PASS=false',
    '  case "$TYPE" in',
    '    file_exists)',
    '      if ls $PATTERN 1>/dev/null 2>&1; then',
    '        PASS=true',
    '      fi',
    '      ;;',
    '    file_nonempty)',
    '      if [ -s "$PATTERN" ] 2>/dev/null; then',
    '        PASS=true',
    '      fi',
    '      ;;',
    '    file_contains)',
    '      MARKER=$(echo "$GATES" | jq -r ".[$i].marker // empty" 2>/dev/null)',
    '      if [ -n "$MARKER" ] && grep -q "$MARKER" "$PATTERN" 2>/dev/null; then',
    '        PASS=true',
    '      fi',
    '      ;;',
    '  esac',
    '',
    '  if [ "$PASS" = false ]; then',
    '    ALL_PASS=false',
    '  else',
    '    ARTIFACTS=$(echo "$ARTIFACTS" | jq --arg a "$ID" \'. += [$a]\')',
    '  fi',
    'done',
    '',
    'if [ "$ALL_PASS" = true ]; then',
    '  if [ "$HAS_COMMAND_GATE" = true ]; then',
    '    # File gates passed but command gates pending — update artifacts only, not passed flag.',
    '    # transition.sh will run command gates and set passed=true on success.',
    '    echo "$STATE" | jq --arg s "$STAGE" --argjson a "$ARTIFACTS" \'.gates[$s].artifacts = $a\' > "$HARNESS/state.json.tmp" && mv "$HARNESS/state.json.tmp" "$HARNESS/state.json"',
    '    echo "[Harness] Stage $STAGE file gates passed. Command gates pending — run transition to verify."',
    '    PENDING_CMDS=$(jq --arg name "$STAGE" -r \'.stages[] | select(.name == $name) | .gates[] | select(.type == "command_exit") | "  - \\(.id): \\(.command) (\\(if .blockOnFail // true then "block" else "warn" end))"\' "$HARNESS/constraints.json" 2>/dev/null)',
    '    if [ -n "$PENDING_CMDS" ]; then',
    '      echo "$PENDING_CMDS"',
    '    fi',
    '  else',
    '    echo "$STATE" | jq --arg s "$STAGE" --argjson a "$ARTIFACTS" \'.gates[$s].passed = true | .gates[$s].artifacts = $a\' > "$HARNESS/state.json.tmp" && mv "$HARNESS/state.json.tmp" "$HARNESS/state.json"',
    '    echo "[Harness] Stage $STAGE gates PASSED. Ready to advance with next slash command."',
    '  fi',
    'fi',
    '',
    'exit 0',
  ].join('\n');
}

// ── Transition script (stage transition) ──

function renderTransitionScript(): string {
  return [
    '#!/usr/bin/env bash',
    '# transition.sh — Stage transition: check gates, update state, switch role',
    '# Called by slash commands: bash .claude/hooks/transition.sh <target-stage>',
    '# In standalone mode: bash .claude/hooks/transition.sh --gate <name> | --command <cmd>',
    '# Exit 0 = success, exit 1 = blocked (gates not passed)',
    '',
    'set -uo pipefail',
    '',
    'HARNESS=".harness"',
    '',
    '# Detect mode: sprint (state.json with sprint.current) or standalone (no sprint context)',
    'detect_mode() {',
    '  if [ -f "$HARNESS/state.json" ]; then',
    '    CURRENT=$(jq -r \'.sprint.current // empty\' "$HARNESS/state.json" 2>/dev/null)',
    '    if [ -n "$CURRENT" ]; then',
    '      echo "sprint"',
    '      return',
    '    fi',
    '  fi',
    '  echo "standalone"',
    '}',
    '',
    'MODE=$(detect_mode)',
    '',
    '# ── Standalone mode: pure gate executor ──',
    'if [ "$MODE" = "standalone" ]; then',
    '  # Standalone gate executor: run a single gate, return exit code',
    '  # Usage: --gate <gate-name> (reads command from constraints.json)',
    '  #    or: --command <cmd> (execute command directly)',
    '',
    '  GATE_NAME=""',
    '  DIRECT_CMD=""',
    '',
    '  while [ $# -gt 0 ]; do',
    '    case "$1" in',
    '      --gate)',
    '        GATE_NAME="$2"',
    '        shift 2',
    '        ;;',
    '      --command)',
    '        DIRECT_CMD="$2"',
    '        shift 2',
    '        ;;',
    '      *)',
    '        shift',
    '        ;;',
    '    esac',
    '  done',
    '',
    '  if [ -n "$DIRECT_CMD" ]; then',
    '    # Direct command execution — language agnostic, any command works',
    '    echo "[Harness:standalone] Running command: $DIRECT_CMD"',
    '    eval "$DIRECT_CMD"',
    '    EXIT_CODE=$?',
    '    if [ $EXIT_CODE -eq 0 ]; then',
    '      echo "[Harness:standalone] PASSED"',
    '    else',
    '      echo "[Harness:standalone] FAILED (exit $EXIT_CODE)" >&2',
    '    fi',
    '    exit $EXIT_CODE',
    '  fi',
    '',
    '  if [ -n "$GATE_NAME" ]; then',
    '    # Resolve command from constraints.json by gate ID',
    '    if [ ! -f "$HARNESS/constraints.json" ]; then',
    '      echo "ERROR: .harness/constraints.json not found. Use --command for direct execution." >&2',
    '      exit 1',
    '    fi',
    '',
    '    if ! command -v jq >/dev/null 2>&1; then',
    '      echo "ERROR: jq is required to resolve gates. Install: brew install jq" >&2',
    '      exit 1',
    '    fi',
    '',
    '    CMD=$(jq -r --arg id "$GATE_NAME" \\',
    '      \'.stages[].gates[] | select(.id == $id and .type == "command_exit") | .command // empty\' \\',
    '      "$HARNESS/constraints.json" 2>/dev/null | head -1)',
    '',
    '    if [ -z "$CMD" ]; then',
    '      echo "ERROR: Gate \'$GATE_NAME\' not found in constraints.json" >&2',
    '      echo "Available gates:" >&2',
    '      jq -r \'.stages[].gates[] | select(.type == "command_exit") | "  \\(.id): \\(.command)"\' "$HARNESS/constraints.json" 2>/dev/null >&2',
    '      exit 1',
    '    fi',
    '',
    '    echo "[Harness:standalone] Running gate: $GATE_NAME → $CMD"',
    '    eval "$CMD"',
    '    EXIT_CODE=$?',
    '    if [ $EXIT_CODE -eq 0 ]; then',
    '      echo "[Harness:standalone] PASSED: $GATE_NAME"',
    '    else',
    '      echo "[Harness:standalone] FAILED: $GATE_NAME (exit $EXIT_CODE)" >&2',
    '    fi',
    '    exit $EXIT_CODE',
    '  fi',
    '',
    '  # No args in standalone mode — show usage + available gates',
    '  echo "Standalone mode. Usage:" >&2',
    '  echo "  bash .claude/hooks/transition.sh --gate <gate-name>" >&2',
    '  echo "  bash .claude/hooks/transition.sh --command \\"<shell-command>\\"" >&2',
    '  if [ -f "$HARNESS/constraints.json" ] && command -v jq >/dev/null 2>&1; then',
    '    echo "" >&2',
    '    echo "Available gates:" >&2',
    '    jq -r \'.stages[].gates[] | select(.type == "command_exit") | "  \\(.id): \\(.command)"\' "$HARNESS/constraints.json" 2>/dev/null >&2',
    '  fi',
    '  exit 1',
    'fi',
    '',
    '# ── Sprint mode: existing transition logic below ──',
    '',
    'TARGET="${1:-}"',
    '',
    'if [ -z "$TARGET" ]; then',
    '  echo "Usage: bash .claude/hooks/transition.sh <target-stage>" >&2',
    '  exit 1',
    'fi',
    '',
    'if [ ! -f "$HARNESS/state.json" ] || [ ! -f "$HARNESS/constraints.json" ]; then',
    '  echo "ERROR: .harness/ not initialized. Run session-init.sh first." >&2',
    '  exit 1',
    'fi',
    '',
    'if ! command -v jq >/dev/null 2>&1; then',
    '  echo "ERROR: jq is required. Install with: brew install jq" >&2',
    '  exit 1',
    'fi',
    '',
    'STATE=$(cat "$HARNESS/state.json")',
    'CURRENT=$(echo "$STATE" | jq -r \'.sprint.current\')',
    '',
    'if [ "$CURRENT" = "$TARGET" ]; then',
    '  echo "Already in $TARGET stage."',
    '  exit 0',
    'fi',
    '',
    '# Check if transition rule exists',
    'TRANSITION_COUNT=$(jq --arg from "$CURRENT" --arg to "$TARGET" \\',
    '  \'[.transitions[] | select(.from == $from and .to == $to)] | length\' \\',
    '  "$HARNESS/constraints.json" 2>/dev/null)',
    '',
    'if [ "$TRANSITION_COUNT" -eq 0 ] 2>/dev/null; then',
    '  echo "BLOCKED: No valid transition from $CURRENT to $TARGET" >&2',
    '  echo "Check .harness/constraints.json for valid stage order." >&2',
    '  exit 1',
    'fi',
    '',
    '# Check required gates — empty requires means auto-advance',
    'REQUIRES=$(jq --arg from "$CURRENT" --arg to "$TARGET" \\',
    '  \'.transitions[] | select(.from == $from and .to == $to) | .requires[]\' \\',
    '  "$HARNESS/constraints.json" 2>/dev/null)',
    '',
    '# Check if current stage has command gates — if so, gate.passed might be false',
    '# even though file gates passed. We run command gates below before transitioning.',
    'HAS_CMD_GATE=$(jq --arg name "$CURRENT" \'[.stages[] | select(.name == $name) | .gates[] | select(.type == "command_exit")] | length\' "$HARNESS/constraints.json" 2>/dev/null)',
    '',
    'if [ -n "$REQUIRES" ]; then',
    '  BLOCKED=""',
    '  for gate in $REQUIRES; do',
    '    PASSED=$(echo "$STATE" | jq -r ".gates.\\"$CURRENT\\".passed // false")',
    '    if [ "$PASSED" != "true" ]; then',
    '      BLOCKED="$BLOCKED  - $gate\\n"',
    '    fi',
    '  done',
    '',
    '  if [ -n "$BLOCKED" ] && [ "$HAS_CMD_GATE" = "0" ]; then',
    '    echo "BLOCKED: Cannot advance from $CURRENT to $TARGET" >&2',
    '    echo "Required gates not passed:" >&2',
    '    echo -e "$BLOCKED" >&2',
    '    echo "Run: bash .harness/scripts/check.sh" >&2',
    '    exit 1',
    '  fi',
    'fi',
    '',
    '# Run command_exit gates for current stage (deferred from advance.sh for performance)',
    'COMMAND_GATES=$(jq --arg name "$CURRENT" \'[.stages[] | select(.name == $name) | .gates[] | select(.type == "command_exit")]\' "$HARNESS/constraints.json" 2>/dev/null)',
    'CMD_COUNT=$(echo "$COMMAND_GATES" | jq \'length\' 2>/dev/null)',
    'if [ "$CMD_COUNT" -gt 0 ] 2>/dev/null; then',
    '  for i in $(seq 0 $((CMD_COUNT - 1))); do',
    '    CMD=$(echo "$COMMAND_GATES" | jq -r ".[$i].command // empty" 2>/dev/null)',
    '    CMD_ID=$(echo "$COMMAND_GATES" | jq -r ".[$i].id // empty" 2>/dev/null)',
    '    BLOCK=$(echo "$COMMAND_GATES" | jq -r ".[$i].blockOnFail // true" 2>/dev/null)',
    '    if [ -n "$CMD" ]; then',
    '      echo "[Harness] Running command gate: $CMD"',
    '      if ! eval "$CMD"; then',
    '        if [ "$BLOCK" = "true" ]; then',
    '          echo "BLOCKED: Command gate \\"$CMD_ID\\" failed: $CMD" >&2',
    '          exit 1',
    '        else',
    '          echo "[Harness] WARNING: Command gate \\"$CMD_ID\\" failed (non-blocking): $CMD" >&2',
    '          mkdir -p "$HARNESS/log"',
    '          printf \'{"ts":"%s","gate":"%s","command":"%s","status":"warn"}\\n\' \\',
    '            "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$CMD_ID" "$CMD" >> "$HARNESS/log/gate-warnings.jsonl"',
    '        fi',
    '      else',
    '        echo "[Harness] Command gate passed: $CMD_ID"',
    '      fi',
    '    fi',
    '  done',
    'fi',
    '',
    '# Mark current stage gates as passed (covers command gate stages where advance.sh deferred)',
    'STATE=$(cat "$HARNESS/state.json")',
    'STATE=$(echo "$STATE" | jq --arg s "$CURRENT" \'.gates[$s].passed = true\')',
    'echo "$STATE" > "$HARNESS/state.json.tmp" && mv "$HARNESS/state.json.tmp" "$HARNESS/state.json"',
    '',
    '# Transition allowed — update state',
    'NEW_STATE=$(echo "$STATE" | jq --arg t "$TARGET" \'',
    '  .sprint.history += [.sprint.current] |',
    '  .sprint.current = $t',
    '\')',
    '',
    '# Update role from target stage config',
    'NEW_ROLE=$(jq --arg name "$TARGET" \'.stages[] | select(.name == $name) | .roles[0]\' "$HARNESS/constraints.json" 2>/dev/null)',
    'NEW_TOOLS=$(jq --arg name "$TARGET" \'.stages[] | select(.name == $name) | .tools.allow\' "$HARNESS/constraints.json" 2>/dev/null)',
    'NEW_PATHS=$(jq --arg name "$TARGET" \'.stages[] | select(.name == $name) | .paths.write\' "$HARNESS/constraints.json" 2>/dev/null)',
    '',
    'NEW_STATE=$(echo "$NEW_STATE" | jq --arg r "$NEW_ROLE" --argjson t "$NEW_TOOLS" --argjson p "$NEW_PATHS" \'',
    '  .role.current = $r |',
    '  .role.allowed_tools = $t |',
    '  .role.allowed_paths = $p',
    '\')',
    '',
    'echo "$NEW_STATE" > "$HARNESS/state.json.tmp" && mv "$HARNESS/state.json.tmp" "$HARNESS/state.json"',
    '',
    '# Update legacy files for backward compatibility (emit-event.sh reads these)',
    'echo "$TARGET" > .harness/current-stage',
    'echo "$NEW_ROLE" > .harness/current-role',
    '',
    '# Activate sprint guard — enforce write path/tool restrictions for this stage',
    'touch "$HARNESS/sprint-guard-active"',
    '',
    '# Clear any active skill bypass — sprint rules resume on transition',
    'rm -f "$HARNESS/skill-bypass"',
    '',
    'echo "Transitioned: $CURRENT → $TARGET (role: $NEW_ROLE)"',
    'echo "Run /$TARGET to begin the next stage."',
    'if [ "$TARGET" = "review" ]; then',
    '  echo "Tip: Run /code-review for a deep code quality audit."',
    'fi',
    '',
    'exit 0',
  ].join('\n');
}

// ── Main generator ──

export function generateClaudeHooks(_config: ProjectConfig): OutputFile[] {
  const files: OutputFile[] = [];

  // P1: Log layer — emitEvent on every tool use
  files.push({
    path: '.claude/hooks/emit-event.sh',
    content: renderEmitEventScript(),
  });

  // P1: Hands layer — guard enforces stage/role constraints from constraints.json
  files.push({
    path: '.claude/hooks/guard.sh',
    content: renderGuardScript(),
  });

  // PostToolUse: check gates and update state.json
  files.push({
    path: '.claude/hooks/advance.sh',
    content: renderAdvanceScript(),
  });

  // Stage transition: check gates, update state, switch role
  files.push({
    path: '.claude/hooks/transition.sh',
    content: renderTransitionScript(),
  });

  return files;
}

// ── Hook registrations for settings.json ──

export function buildClaudeHookRegistrations(
  config: ProjectConfig
): Record<string, Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>> {
  const registrations: Record<
    string,
    Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>
  > = {};

  // PreToolUse: guard.sh — enforce stage/role/tool constraints + dangerous command blocking
  registrations['PreToolUse'] = [
    {
      matcher: '',
      hooks: [{ type: 'command', command: '.claude/hooks/guard.sh' }],
    },
  ];

  // PostToolUse: advance.sh — check gates after each tool use
  registrations['PostToolUse'] = [
    {
      matcher: '',
      hooks: [{ type: 'command', command: '.claude/hooks/advance.sh' }],
    },
  ];

  // Keep emit-event for logging (on write-like operations only)
  for (const tool of ['Write', 'Edit', 'Bash']) {
    registrations['PostToolUse'].push({
      matcher: tool,
      hooks: [{ type: 'command', command: '.claude/hooks/emit-event.sh' }],
    });
  }

  // Secret detection hook (vault credential policy)
  if (hasSecretCheck(config)) {
    registrations['PreToolUse'].push({
      matcher: 'Write',
      hooks: [{ type: 'command', command: '.claude/hooks/secret-check.sh' }],
    });
  }

  // Session save hook (git-based session storage)
  if (config.architecture.session.storage === 'git-based') {
    for (const tool of ['Write', 'Edit', 'Bash']) {
      registrations['PostToolUse'].push({
        matcher: tool,
        hooks: [{ type: 'command', command: '.claude/scripts/session-save.sh' }],
      });
    }
  }

  // Merge user-defined hooks from config.integration.hooks
  for (const hook of config.integration.hooks) {
    if (!registrations[hook.event]) {
      registrations[hook.event] = [];
    }
    registrations[hook.event].push({
      matcher: '',
      hooks: [{ type: 'command', command: hook.command }],
    });
  }

  return registrations;
}
