import type { ProjectConfig, OutputFile } from '@/types';
import { getNegotiationRoles } from '@/generators/core/negotiation';

// ── Negotiate script: workspace setup and verification for multi-role negotiation ──

export function generateNegotiateScript(config: ProjectConfig): OutputFile | null {
  // Only generate if at least one stage has negotiation roles
  const hasNegotiation = config.flow.sprint.some(
    (s) => s.enabled && getNegotiationRoles(s.name, s.roles, s.negotiationRoles).length >= 2
  );
  if (!hasNegotiation) return null;

  const content = [
    '#!/usr/bin/env bash',
    '# negotiate.sh — Prepare and verify negotiation workspace for multi-role stages',
    '# Usage:',
    '#   negotiate.sh init <stage> <role1,role2,...>  — Create round directories + manifest',
    '#   negotiate.sh check-round <1|2>               — Verify all role files exist for round',
    '#   negotiate.sh status                          — Show negotiation progress',
    '',
    'set -uo pipefail',
    '',
    'NEG_DIR="docs/negotiation"',
    'MANIFEST="$NEG_DIR/manifest.json"',
    '',
    'cmd="${1:-}"',
    'shift || true',
    '',
    '# ── Input validation ──',
    'validate_stage() {',
    '  echo "$1" | grep -qE "^[a-z][a-z0-9-]*$" && return 0',
    '  echo "ERROR: Invalid stage name: $1 (must be lowercase alphanumeric with dashes)" >&2',
    '  return 1',
    '}',
    '',
    'validate_roles() {',
    '  echo "$1" | grep -qE "^[a-z0-9-]+(,[a-z0-9-]+)*$" && return 0',
    '  echo "ERROR: Invalid roles: $1 (must be comma-separated lowercase alphanumeric)" >&2',
    '  return 1',
    '}',
    '',
    'require_jq() {',
    '  if ! command -v jq >/dev/null 2>&1; then',
    '    echo "ERROR: jq is required. Install: brew install jq" >&2',
    '    return 1',
    '  fi',
    '}',
    '',
    '# ── init ──',
    'if [ "$cmd" = "init" ]; then',
    '  STAGE="${1:-}"',
    '  ROLES_CSV="${2:-}"',
    '',
    '  if [ -z "$STAGE" ] || [ -z "$ROLES_CSV" ]; then',
    '    echo "Usage: negotiate.sh init <stage> <role1,role2,...>" >&2',
    '    exit 1',
    '  fi',
    '',
    '  validate_stage "$STAGE" || exit 1',
    '  validate_roles "$ROLES_CSV" || exit 1',
    '  require_jq || exit 1',
    '',
    '  mkdir -p "$NEG_DIR/round-1" "$NEG_DIR/round-2"',
    '',
    '  ROLES_JSON=$(echo "$ROLES_CSV" | tr "," "\\n" | jq -R . | jq -s .)',
    '  printf \'{"stage":"%s","roles":%s,"round":0}\\n\' "$STAGE" "$ROLES_JSON" > "$MANIFEST"',
    '',
    '  IFS="," read -ra ROLE_ARRAY <<< "$ROLES_CSV"',
    '  for ROLE in "${ROLE_ARRAY[@]}"; do',
    '    touch "$NEG_DIR/round-1/${ROLE}.md"',
    '    touch "$NEG_DIR/round-2/${ROLE}.md"',
    '  done',
    '',
    '  echo "Negotiation workspace initialized for stage: $STAGE"',
    '  echo "Roles: ${ROLES_CSV//,/ }"',
    '  echo "Workspace: $NEG_DIR/"',
    '  exit 0',
    'fi',
    '',
    '# ── check-round ──',
    'if [ "$cmd" = "check-round" ]; then',
    '  ROUND="${1:-}"',
    '',
    '  if [ "$ROUND" != "1" ] && [ "$ROUND" != "2" ]; then',
    '    echo "Usage: negotiate.sh check-round <1|2>" >&2',
    '    exit 1',
    '  fi',
    '',
    '  if [ ! -f "$MANIFEST" ]; then',
    '    echo "ERROR: No negotiation manifest found. Run: negotiate.sh init <stage> <roles>" >&2',
    '    exit 1',
    '  fi',
    '',
    '  require_jq || exit 1',
    '',
    '  MISSING=""',
    '  COMPLETE=0',
    '  TOTAL=0',
    '',
    '  while IFS= read -r ROLE; do',
    '    TOTAL=$((TOTAL + 1))',
    '    FILE="$NEG_DIR/round-${ROUND}/${ROLE}.md"',
    '    if [ ! -s "$FILE" ]; then',
    '      MISSING="$MISSING  - $ROLE\\n"',
    '    else',
    '      COMPLETE=$((COMPLETE + 1))',
    '    fi',
    '  done < <(jq -r \'.roles[]\' "$MANIFEST" 2>/dev/null)',
    '',
    '  if [ -n "$MISSING" ]; then',
    '    echo "Round $ROUND incomplete: ${COMPLETE}/${TOTAL} submitted"',
    '    echo -e "Missing:\\n$MISSING"',
    '    exit 1',
    '  fi',
    '',
    '  echo "Round $ROUND complete: ${COMPLETE}/${TOTAL} submitted"',
    '  exit 0',
    'fi',
    '',
    '# ── status ──',
    'if [ "$cmd" = "status" ]; then',
    '  if [ ! -f "$MANIFEST" ]; then',
    '    echo "No active negotiation. Run: negotiate.sh init <stage> <roles>"',
    '    exit 0',
    '  fi',
    '',
    '  if command -v jq >/dev/null 2>&1; then',
    '    STAGE=$(jq -r \'.stage // "unknown"\' "$MANIFEST")',
    '    echo "Stage: $STAGE"',
    '  else',
    '    echo "Stage: (jq missing, cannot parse manifest)"',
    '  fi',
    '  echo ""',
    '',
    '  for ROUND in 1 2; do',
    '    echo "Round $ROUND:"',
    '    if command -v jq >/dev/null 2>&1; then',
    '      while IFS= read -r ROLE; do',
    '        FILE="$NEG_DIR/round-${ROUND}/${ROLE}.md"',
    '        if [ -s "$FILE" ]; then',
    '          SIZE=$(wc -c < "$FILE" | tr -d " ")',
    '          echo "  √ $ROLE (${SIZE} bytes)"',
    '        else',
    '          echo "  · $ROLE (pending)"',
    '        fi',
    '      done < <(jq -r \'.roles[]\' "$MANIFEST" 2>/dev/null)',
    '    else',
    '      echo "  (jq missing)"',
    '    fi',
    '    echo ""',
    '  done',
    '',
    '  if [ -s "$NEG_DIR/consensus.md" ]; then',
    '    echo "Consensus: √ written"',
    '  else',
    '    echo "Consensus: · pending"',
    '  fi',
    '',
    '  exit 0',
    'fi',
    '',
    '# ── unknown command ──',
    'echo "Usage: negotiate.sh <init|check-round|status>" >&2',
    'echo "  init <stage> <role1,role2,...>  — Create workspace" >&2',
    'echo "  check-round <1|2>               — Verify round completeness" >&2',
    'echo "  status                          — Show progress" >&2',
    'exit 1',
  ].join('\n');

  return {
    path: '.claude/scripts/negotiate.sh',
    content,
  };
}
