import type { TemplatePreset } from '@/types';

export const gstackSprint: TemplatePreset = {
  id: 'gstack-sprint',
  name: 'GStack Sprint',
  description: 'Full 7-stage sprint with all roles. Team-scale delivery pipeline inspired by GStack methodology.',
  icon: '🚀',
  config: {
    architecture: {
      session: { storage: 'git-based', eventRetention: 200, recoveryStrategy: 'last-checkpoint' },
      harness: { engine: 'claude-code', contextStrategy: 'sliding-window', maxRetries: 5 },
      sandbox: { type: 'docker', mcpServers: [], credentialPolicy: 'bundled' },
    },
    flow: {
      sprint: [
        { id: 'think', name: 'think', order: 0, enabled: true, roles: ['ceo'],
          gates: ['Problem statement defined', 'Success metrics agreed'],
          stageConfig: { dimensions: ['problem-framing', 'success-metrics', 'constraints', 'alternatives', 'scope', 'risks'], depth: 'deep' } },
        { id: 'plan', name: 'plan', order: 1, enabled: true, roles: ['ceo', 'designer'],
          gates: ['Architecture doc approved', 'UI wireframes signed off'],
          stageConfig: { reviewTypes: ['ceo-review', 'eng-review', 'design-review', 'dx-review'], taskStructure: 'structured' } },
        { id: 'build', name: 'build', order: 2, enabled: true, roles: ['eng-manager'],
          gates: ['Feature branch created', 'Core logic implemented'],
          stageConfig: { executionStrategy: 'subagent-parallel', tddMode: 'enforced' } },
        { id: 'review', name: 'review', order: 3, enabled: true, roles: ['eng-manager'],
          gates: ['Code review passed', 'No critical code smells'],
          stageConfig: { reviewDimensions: ['spec-compliance', 'code-quality', 'security'], autoFix: 'auto', severityThreshold: 'critical-major' } },
        { id: 'test', name: 'test', order: 4, enabled: true, roles: ['qa'],
          gates: ['All test cases executed', 'Zero critical defects', 'Performance benchmarks met'],
          stageConfig: { testMethods: ['tdd', 'regression'], coverageTarget: 80, testTypes: ['unit', 'integration', 'e2e', 'browser'], environment: 'staging', testCommand: '', coverageCommand: '' } },
        { id: 'ship', name: 'ship', order: 5, enabled: true, roles: ['release'],
          gates: ['CI pipeline green', 'Changelog updated', 'Release tag created'],
          stageConfig: { pipeline: ['run-tests', 'create-pr', 'merge', 'deploy'], versionStrategy: 'semver-minor', deploymentTargets: ['staging', 'production'] } },
        { id: 'reflect', name: 'reflect', order: 6, enabled: true, roles: ['eng-manager'],
          gates: ['Retrospective notes written', 'Action items documented'],
          stageConfig: { dimensions: ['velocity', 'quality', 'test-health', 'growth'], persistLearning: 'project-memory' } },
      ],
      roles: [
        { id: 'ceo', label: 'CEO / Product Lead', description: 'Defines vision, prioritizes features, and drives decision-making.', defaultConstraints: ['Must approve all scope changes'],
          reviewFocus: ['user value', 'scope alignment', 'business impact', 'priority'],
          systemPrompt: 'You are the CEO / Product Lead. Challenge scope creep aggressively. Approve only what delivers measurable value. You have veto power on any stage gate.' },
        { id: 'designer', label: 'Designer', description: 'Owns UX flows, wireframes, and design system consistency.', defaultConstraints: ['All designs must pass accessibility audit'],
          reviewFocus: ['UX quality', 'accessibility', 'design system consistency', 'user flows'],
          systemPrompt: 'You are the Designer. Evaluate every output for interaction consistency, accessibility compliance, and design system alignment. You can block release on accessibility grounds.' },
        { id: 'eng-manager', label: 'Engineering Manager', description: 'Leads development, reviews code, and manages technical debt.', defaultConstraints: ['Must maintain test coverage above 80%'],
          reviewFocus: ['architecture', 'code quality', 'technical debt', 'testability'],
          systemPrompt: 'You are the Eng Manager. Evaluate every technical decision for maintainability, testability, and architectural soundness. Identify technical debt early.' },
        { id: 'qa', label: 'QA Engineer', description: 'Ensures quality through testing strategies and defect triage.', defaultConstraints: ['Must log all test results'],
          reviewFocus: ['test coverage', 'edge cases', 'regression risk', 'evidence quality'],
          systemPrompt: 'You are the QA Engineer. Verify through evidence, not claims. Identify untested edge cases and regression risks. You can block release on quality grounds.' },
        { id: 'release', label: 'Release Engineer', description: 'Manages CI/CD pipelines, deployments, and release artifacts.', defaultConstraints: ['Must follow semantic versioning'],
          reviewFocus: ['pipeline integrity', 'version compatibility', 'rollback plan', 'deployment safety'],
          systemPrompt: 'You are the Release Engineer. Verify all gates pass before deployment. Ensure rollback plans exist for every release. Enforce semantic versioning.' },
      ],
      constraints: [
        { id: 'no-skip-stages', stageId: '*', type: 'gate', description: 'No stage may be skipped — all must run in order.', enforced: true },
        { id: 'review-required', stageId: 'ship', type: 'gate', description: 'At least one code review approval required before shipping.', enforced: true,
          enforcement: { checkType: 'file-contains', targets: ['docs/reviews/review-report.md'], pattern: '## Sign-offs', message: 'No code review sign-offs found in review report' } },
      ],
    },
  },
};
