import type { ProjectConfig, OutputFile, ConstraintType, Language } from '@/types';
import { getStageArtifacts } from './stageArtifacts';

// ── Simple YAML helpers (reuse pattern from config.ts) ──

function yamlString(value: string): string {
  if (value === '') return '""';
  if (/^[{}[\],&*?|>!%@`#:'"\\\-]/.test(value) || value.includes(': ') || value.includes(' #') || /^(true|false|null|yes|no|on|off|~)$/i.test(value)) {
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }
  return value;
}

function yamlValue(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return yamlString(value);
  return yamlString(String(value));
}

function yamlList(items: string[], indent: number): string {
  const pad = ' '.repeat(indent);
  return items.map((item) => `${pad}- ${yamlValue(item)}`).join('\n');
}

function yamlBlock(obj: Record<string, unknown>, indent: number): string {
  const pad = ' '.repeat(indent);
  const lines: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    if (Array.isArray(value)) {
      if (value.length === 0) continue;
      lines.push(`${pad}${key}:`);
      for (const item of value) {
        if (typeof item === 'string') {
          lines.push(`${pad}  - ${yamlValue(item)}`);
        }
      }
    } else if (typeof value === 'string') {
      lines.push(`${pad}${key}: ${yamlValue(value)}`);
    } else if (typeof value === 'boolean') {
      lines.push(`${pad}${key}: ${yamlValue(value)}`);
    } else if (typeof value === 'number') {
      lines.push(`${pad}${key}: ${value}`);
    } else if (value === null || value === undefined) {
      continue;
    }
  }
  return lines.join('\n');
}

interface ConstraintEntry {
  id: string;
  stageId: string;
  type: string;
  description: string;
  enforced: boolean;
  enforcement?: {
    checkType: string;
    targets?: string[];
    pattern?: string;
    message?: string;
  };
}

function serializeConstraintList(entries: ConstraintEntry[]): string {
  if (entries.length === 0) return '';
  const lines: string[] = [];
  for (const entry of entries) {
    lines.push(`- id: ${yamlValue(entry.id)}`);
    lines.push(`  stageId: ${yamlValue(entry.stageId)}`);
    lines.push(`  type: ${yamlValue(entry.type)}`);
    lines.push(`  description: ${yamlValue(entry.description)}`);
    lines.push(`  enforced: ${yamlValue(entry.enforced)}`);
    if (entry.enforcement) {
      lines.push(`  enforcement:`);
      lines.push(`    checkType: ${yamlValue(entry.enforcement.checkType)}`);
      if (entry.enforcement.targets) {
        lines.push(`    targets:`);
        for (const t of entry.enforcement.targets) {
          lines.push(`      - ${yamlValue(t)}`);
        }
      }
      if (entry.enforcement.pattern) {
        lines.push(`    pattern: ${yamlValue(entry.enforcement.pattern)}`);
      }
      if (entry.enforcement.message) {
        lines.push(`    message: ${yamlValue(entry.enforcement.message)}`);
      }
    }
  }
  return lines.join('\n') + '\n';
}

// ── Stage tool rules for hook state machine ──

interface StageToolRules {
  allow: string[];
  deny: string[];
  writePaths: string[];
}

function getStageToolRules(stageName: string): StageToolRules {
  switch (stageName) {
    case 'think':
      return { allow: ['Read', 'Grep', 'Glob', 'Agent'], deny: ['Write', 'Edit', 'Bash'], writePaths: ['docs/**'] };
    case 'plan':
      return { allow: ['Read', 'Grep', 'Glob', 'Write', 'Edit', 'Agent'], deny: ['Bash'], writePaths: ['docs/**'] };
    case 'build':
      return { allow: ['Read', 'Grep', 'Glob', 'Write', 'Edit', 'Bash', 'Agent'], deny: [], writePaths: ['src/**', 'test/**', 'docs/**'] };
    case 'review':
      return { allow: ['Read', 'Grep', 'Glob', 'Write', 'Edit'], deny: ['Bash'], writePaths: ['docs/**'] };
    case 'test':
      return { allow: ['Read', 'Grep', 'Glob', 'Write', 'Edit', 'Bash'], deny: [], writePaths: ['test/**', 'docs/**'] };
    case 'ship':
      return { allow: ['Read', 'Grep', 'Glob', 'Write', 'Edit', 'Bash'], deny: [], writePaths: ['**'] };
    case 'reflect':
      return { allow: ['Read', 'Grep', 'Glob', 'Write', 'Edit'], deny: ['Bash'], writePaths: ['docs/**'] };
    default:
      return { allow: [], deny: [], writePaths: [] };
  }
}

// ── Unified constraints.yaml generator ──

function generateConstraintsYaml(config: ProjectConfig): string {
  const enabledStages = config.flow.sprint
    .filter((s) => s.enabled)
    .sort((a, b) => a.order - b.order);

  if (enabledStages.length === 0) return '';

  const lines: string[] = [
    '# .harness/constraints.yaml — Declarative constraint rules for hook state machine',
    '# Generated by Harness Forge. DO NOT EDIT manually.',
    `project: ${yamlValue(config.project.name || 'unnamed')}`,
    '',
    'stages:',
  ];

  for (let i = 0; i < enabledStages.length; i++) {
    const stage = enabledStages[i];
    const nextStage = enabledStages[i + 1];
    const artifacts = getStageArtifacts(stage);

    lines.push(`  - name: ${yamlValue(stage.name)}`);
    lines.push(`    roles:`);
    for (const role of stage.roles) {
      lines.push(`      - ${yamlValue(role)}`);
    }

    const toolRules = getStageToolRules(stage.name);
    lines.push(`    tools:`);
    lines.push(`      allow:`);
    for (const tool of toolRules.allow) {
      lines.push(`        - ${yamlValue(tool)}`);
    }
    lines.push(`      deny:`);
    for (const tool of toolRules.deny) {
      lines.push(`        - ${yamlValue(tool)}`);
    }

    lines.push(`    paths:`);
    lines.push(`      write:`);
    for (const p of toolRules.writePaths) {
      lines.push(`        - ${yamlValue(p)}`);
    }

    lines.push(`    gates:`);
    if (artifacts.length > 0) {
      for (const artifact of artifacts) {
        const gateId = `${stage.name}-${artifact.path.split('/').pop()?.replace(/\..*$/, '') ?? 'output'}`;
        lines.push(`      - id: ${yamlValue(gateId)}`);
        if (artifact.verification === 'exists') {
          lines.push(`        type: file_exists`);
        } else if (artifact.verification === 'non-empty') {
          lines.push(`        type: file_nonempty`);
        } else {
          lines.push(`        type: file_contains`);
          lines.push(`        marker: ${yamlValue(artifact.sectionMarker ?? '')}`);
        }
        lines.push(`        pattern: ${yamlValue(artifact.path)}`);
        lines.push(`        description: ${yamlValue(artifact.description)}`);
      }
    }

    const enforcedConstraints = config.flow.constraints.filter(
      (c) => c.enforced && (c.stageId === stage.id || c.stageId === stage.name)
    );
    for (const c of enforcedConstraints) {
      if (c.enforcement?.checkType === 'file-exists' && c.enforcement.targets) {
        for (const target of c.enforcement.targets) {
          lines.push(`      - id: ${yamlValue(c.id)}`);
          lines.push(`        type: file_exists`);
          lines.push(`        pattern: ${yamlValue(target)}`);
          lines.push(`        description: ${yamlValue(c.enforcement.message ?? c.description)}`);
        }
      } else if (c.enforcement?.checkType === 'file-contains' && c.enforcement.targets) {
        for (const target of c.enforcement.targets) {
          lines.push(`      - id: ${yamlValue(c.id)}`);
          lines.push(`        type: file_contains`);
          lines.push(`        pattern: ${yamlValue(target)}`);
          if (c.enforcement.pattern) {
            lines.push(`        marker: ${yamlValue(c.enforcement.pattern)}`);
          }
          lines.push(`        description: ${yamlValue(c.enforcement.message ?? c.description)}`);
        }
      }
    }

    lines.push(`    next: ${yamlValue(nextStage?.name ?? 'null')}`);
    if (i < enabledStages.length - 1) {
      lines.push('');
    }
  }

  lines.push('', 'roles:');
  for (const role of config.flow.roles) {
    lines.push(`  ${role.id}:`);
    lines.push(`    description: ${yamlValue(role.description)}`);
    if (role.reviewFocus && role.reviewFocus.length > 0) {
      lines.push(`    focus:`);
      for (const f of role.reviewFocus) {
        lines.push(`      - ${yamlValue(f)}`);
      }
    }
  }

  lines.push('', 'transitions:');
  for (let i = 0; i < enabledStages.length - 1; i++) {
    const from = enabledStages[i];
    const to = enabledStages[i + 1];
    const fromArtifacts = getStageArtifacts(from);

    lines.push(`  - from: ${yamlValue(from.name)}`);
    lines.push(`    to: ${yamlValue(to.name)}`);
    lines.push(`    requires:`);

    for (const artifact of fromArtifacts) {
      const gateId = `${from.name}-${artifact.path.split('/').pop()?.replace(/\..*$/, '') ?? 'output'}`;
      lines.push(`      - ${yamlValue(gateId)}`);
    }
    const enforcedConstraints = config.flow.constraints.filter(
      (c) => c.enforced && (c.stageId === from.id || c.stageId === from.name)
    );
    for (const c of enforcedConstraints) {
      lines.push(`      - ${yamlValue(c.id)}`);
    }
  }

  return lines.join('\n') + '\n';
}

// ── Initial state.json generator ──

function generateInitialState(config: ProjectConfig): string {
  const enabledStages = config.flow.sprint
    .filter((s) => s.enabled)
    .sort((a, b) => a.order - b.order);

  const firstStage = enabledStages[0];
  const firstRole = firstStage?.roles[0] ?? 'ceo';
  const firstToolRules = firstStage ? getStageToolRules(firstStage.name) : { allow: [] as string[], writePaths: [] as string[] };

  const gates: Record<string, { passed: boolean; artifacts: string[] }> = {};
  for (const stage of enabledStages) {
    gates[stage.name] = { passed: false, artifacts: [] };
  }

  const state = {
    version: 1,
    project: config.project.name || 'unnamed',
    sprint: {
      current: firstStage?.name ?? 'think',
      history: [] as string[],
      started_at: '',
    },
    role: {
      current: firstRole,
      allowed_tools: firstToolRules.allow,
      allowed_paths: firstToolRules.writePaths,
    },
    gates,
  };

  return JSON.stringify(state, null, 2) + '\n';
}

// ── Constraint type to filename mapping ──

const CONSTRAINT_FILES: Record<ConstraintType, string> = {
  gate: 'gates.yaml',
  checklist: 'checklists.yaml',
  'output-requirement': 'outputs.yaml',
};

// ── Language-based test command defaults ──

const LANGUAGE_TEST_DEFAULTS: Record<string, { test: string; coverage: string }> = {
  typescript: { test: 'npm test', coverage: 'npm run coverage' },
  javascript: { test: 'npm test', coverage: 'npm run coverage' },
  python:     { test: 'pytest', coverage: 'pytest --cov --cov-report=term-missing' },
  go:         { test: 'go test ./...', coverage: 'go test -cover ./...' },
  java:       { test: 'mvn test', coverage: 'mvn test jacoco:report' },
  rust:       { test: 'cargo test', coverage: 'cargo tarpaulin' },
  dart:       { test: 'flutter test', coverage: 'flutter test --coverage' },
};

export function generateCoreConstraints(config: ProjectConfig): OutputFile[] {
  const constraints = config.flow.constraints;
  if (constraints.length === 0) return [];

  // Group by type
  const grouped = new Map<ConstraintType, ConstraintEntry[]>();
  for (const c of constraints) {
    const list = grouped.get(c.type) || [];
    list.push({
      id: c.id,
      stageId: c.stageId,
      type: c.type,
      description: c.description,
      enforced: c.enforced,
      enforcement: c.enforcement,
    });
    grouped.set(c.type, list);
  }

  const files: OutputFile[] = [];

  // Generate the unified constraints.yaml for hook state machine
  const constraintsYaml = generateConstraintsYaml(config);
  if (constraintsYaml) {
    files.push({
      path: '.harness/constraints.yaml',
      content: constraintsYaml,
    });
  }

  // Generate initial state.json
  files.push({
    path: '.harness/state.json',
    content: generateInitialState(config),
  });

  for (const [type, entries] of grouped) {
    const filename = CONSTRAINT_FILES[type];
    if (!filename) continue;
    files.push({
      path: `.harness/constraints/${filename}`,
      content: serializeConstraintList(entries),
    });
  }

  // P2-1: Generate machine-readable tdd.yaml when build has tddMode=enforced
  const buildStage = config.flow.sprint.find(
    (s) => s.name === 'build' && s.enabled
  );
  const buildConfig = buildStage?.stageConfig as
    | { tddMode?: string; executionStrategy?: string }
    | undefined;

  if (buildConfig?.tddMode === 'enforced') {
    // Extract test config from the test stage
    const testStage = config.flow.sprint.find(
      (s) => s.name === 'test' && s.enabled
    );
    const testConfig = testStage?.stageConfig as
      | { coverageTarget?: number; testTypes?: string[]; testCommand?: string; coverageCommand?: string }
      | undefined;

    const coverageTarget = testConfig?.coverageTarget ?? 80;
    const testTypes = testConfig?.testTypes ?? ['unit'];

    // Use user-configured commands, falling back to language-based defaults
    const defaults = LANGUAGE_TEST_DEFAULTS[config.project.techStack.language] ?? LANGUAGE_TEST_DEFAULTS.typescript;
    const testCommand = testConfig?.testCommand || defaults.test;
    const coverageCommand = testConfig?.coverageCommand || defaults.coverage;

    const tddYaml = [
      '# .harness/constraints/tdd.yaml',
      '# Machine-readable TDD constraints — parsed by hooks for automated enforcement',
      `version: "1.0"`,
      `stage: build`,
      `coverage:`,
      `  min_percent: ${coverageTarget}`,
      `  measure_command: "${coverageCommand}"`,
      `  result_field: "total.lines.pct"`,
      `tests:`,
      `  must_pass:`,
      ...testTypes.map((t) => `    - ${t}`),
      `  no_skip: true`,
      `  run_command: "${testCommand}"`,
      `retry:`,
      `  max_attempts: ${config.architecture.harness.maxRetries}`,
      `  on_failure: "fix_and_retry"`,
      '',
    ].join('\n');

    files.push({
      path: '.harness/constraints/tdd.yaml',
      content: tddYaml,
    });
  }

  return files;
}
